name = 'agent-friendly-mission'
compatibility_date = "2025-06-01"
assets.directory = "./"
dev.port = 3000
routes = [
  { pattern = "mission.agent-friendly.com", custom_domain = true },
#  { pattern = "www.rendermd.com", custom_domain = true }
]